### ISSUE TITLE
Make CLI client work on Windows

### ISSUE THREAD

**Issue by reibitto** [reibitto/command-center#29]
The blocker for this was this lanterna issue:
https://github.com/mabe02/lanterna/issues/422

But it seems like it's been addressed (at least partially?). It's a matter of trying it on Windows and seeing what happens.

**Comment by rednoah** [comment]
Fully functional as far as I can tell. You'll need to build from source for testing right now though, since none of the maven builds include the new JNA implementation yet.

**Comment by reibitto** [comment]
Thanks @rednoah.

Just to make sure I understood, you mean that lanterna's Windows implementation works as far you can tell? Or did you mean you tried it with Command Center and that it worked?

I'll be setting up my Windows box soon, so I could be try it out myself too.

**Comment by reibitto** [comment]
Looks like it works. Thanks!

I merged the Windows PR.
