### ISSUE TITLE
Allow multiple output for a single command

### ISSUE THREAD

**Issue by tuleism** [reibitto/command-center#35]
Currently, one command can only shows only one output, even though it may have a list:

```
        .sortBy(_.score)(Ordering.Double.TotalOrdering.reverse)
        .distinctBy(_.source)
```

One possible way to do it is:

- `groupBy(_.source)`.
- Sort by score descending, using the highest score within a group.
- If the group with highest score has multiple items, show them all. Otherwise, keep the same behavior.

WDYT?

**Comment by reibitto** [comment]
Oops, that's a bug. Support for multiple results is built-in and supposed to work, but I think I broke it recently with `.distinctBy(_.source)` in attempt to fix a bug elsewhere. Maybe I should revert that change and create a separate issue for the bug I was trying to fix (it was a duplicate display issue).

Thanks for catching that.

**Comment by reibitto** [comment]
Yeah, `distinctBy(_.source)` was the cause. I removed that line for now. I pushed the changes.

**Comment by tuleism** [comment]
Thanks! It shows multiple now.

**Comment by reibitto** [comment]
Alright, I created an issue for the other bug: #37
