### ISSUE TITLE
LocalIPCommand for other OSes

### ISSUE THREAD

**Issue by tuleism** [reibitto/command-center#46]
Currently, to get local IP address, we use:

```scala
localIP <- PCommand("ipconfig", "getifaddr", "en0").string.bimap(CommandError.UnexpectedException, _.trim)
```

It works for macOS, but for Linux the command can vary based on the distro, not to mention Windows. For example, I'm using Manjaro and the default command to list addresses is `ip a`, which then needs some command line magic to extract the IP address.

We can use Java/Scala to get this information. This seems to work with my box (multiple interfaces, running together with docker and VMs)

```scala
val interfaces = NetworkInterface.getNetworkInterfaces.asScala.toList
interfaces.filter { interface =>
  !interface.isLoopback && !interface.isVirtual && interface.isUp
}.flatMap { interface =>
  interface.getInetAddresses.asScala.collect {
    case address: Inet4Address => interface.getDisplayName -> address.getHostAddress
  }
}
```

**Comment by reibitto** [comment]
That is indeed better and cross-platform. That snippet works fine here too. I think that would be a good change.
