### ISSUE TITLE
Stock prices command

### ISSUE THREAD

**Issue by reibitto** [reibitto/command-center#76]
Much like the `time` command, typing `stock` with no args would show you all the configured stocks you're interested in by default in a list.

You would also be able to type `stock [ticker symbol]` to show the price of a specific one. And allow passing in multiple ticker symbols separated by spaces.

**Comment by GKhotyan** [comment]
I'll take this one

**Comment by reibitto** [comment]
Oh, I just noticed there are 2 spaces used in the percent change formatting. It's a minor thing. I can tweak that myself quickly. And maybe make the current stock price + currency the default foreground color to not blend in with the title too much. Hope you don't mind.

**Comment by GKhotyan** [comment]
Of course. I thought about colours, and decided to leave like that. But it's better to find better combination, and may be the same as in other commands
